apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec:
  #completions: 5
  #parallelism: 2
  #activeDeadlineSeconds: 15
  #ttlSecondsAfterFinished: 60
  #suspend: true
  template:
    spec:
      containers:
      - name: resting
        image: busybox
        command: ["/bin/sleep"]
        args: ["3"]
      restartPolicy: Never
