apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: nginx:1.21
    livenessProbe:
      httpGet:
        path: /live
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      periodSeconds: 5
      initialDelaySeconds: 10
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config


