apiVersion: v1
kind: Pod
metadata:
  name: readiness-fail
  labels:
    app: nginx
spec:
  containers:
  - name: liveness
    image: nginx:1.21
    livenessProbe:
      httpGet:
        path: /live
        port: 80
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /fail
        port: 80
      periodSeconds: 5
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
